
web:
  build: .
  working_dir: /data
  command: python aplication.py
  links:
    - db
  volumes:
    - .:/data
  ports:
    - "5050:5050"

db:
  image: postgres:9.3
  environment:
    - POSTGRES_USER=ac3_docker
    - POSTGRES_PASSWORD=456
  ports:
    - "5432:5432"
